services:
  db:
    image: postgres:17-alpine
    container_name: fintech_postgres_db
    environment:
      POSTGRES_DB: fintech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

volumes:
  db_data:
